version: '3.8'

services:
  postgres:
    image: postgres:16.0 # adjusted with production
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: mydatabase # Replace with your desired database name
      POSTGRES_USER: myuser # Replace with your desired username
      POSTGRES_PASSWORD: mypassword # Replace with your desired password
    ports:
      - '5432:5432' # Map PostgreSQL default port
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist data

volumes:
  postgres-data:
    driver: local
